headers/command_line_unit.h File Reference
Обеспечивает ввод аргументов командной строки
Classes
struct Cmd_arg
\breif Структура для работы с заданными аргументами командной строки
Enumerations
enum MODES { SOLVE
, TEST
, HELP
 }
\breif Перечисление режимов работы программы
Functions
void check_args (int argc_cp, char **argv_cp, MODES *mode)
Просматривает аргументы командной строки для дальнейшей работы с каждым из них
void change_mode (MODES *mode, MODES cur_md)
Меняет режим работы программы
int help (void)
Выводит информацию о каждом допустимом аргументе командной строки
Detailed Description
Обеспечивает ввод аргументов командной строки
Enumeration Type Documentation
MODES
enum MODES
\breif Перечисление режимов работы программы
Enumerator
SOLVE Режим решения квадратного уравнения с вводом коэффициентов из консоли
TEST Режим тестирования работы квадратного уравнения
HELP Вывод подсказок для запуска режимов работы
Definition at line 10 of file command_line_unit.h.
           {
    SOLVE,
    TEST,
    HELP
};
Function Documentation
change_mode()
void change_mode (MODES * mode, MODES md)
Меняет режим работы программы
Parameters
 in,out mode Режим работы программы, который будет изменен
 in cur_md Режим работы программы, который будет активирован
Definition at line 60 of file command_line_unit.cpp.
                                        {
    switch (md) {
        case SOLVE:
            *mode = SOLVE;
            break;
        case TEST:
            *mode = TEST;
            break;
        case HELP:
            *mode = HELP;
            break;
        default:
            printf("Ошибка: неопознанный режим работы");
            break;
    }
}
References HELP, SOLVE, and TEST.
Referenced by check_args().
check_args()
void check_args (int argc_cp, char ** argv_cp, MODES * mode)
Просматривает аргументы командной строки для дальнейшей работы с каждым из них
Parameters
 in argc_cp Копия количества аргументов командной строки
 in argv_cp Копия аргументов командной строки
 in,out mode Режим работы, который может быть изменен благодаря аргументам командной строки
Definition at line 27 of file command_line_unit.cpp.
                                                          {
    for (int iter = 0; iter < argc_cp; iter++) {
        for (size_t arg_num = 0; arg_num < sizeof(arg_array)/sizeof(arg_array[0]); arg_num++) {
            if (
                strcmp(arg_array[arg_num].short_name, argv_cp[iter]) == 0 ||
                strcmp(arg_array[arg_num].full_name, argv_cp[iter]) == 0) {
                    change_mode(mode, arg_array[arg_num].mode);
            }
        }
    }
}
References arg_array, and change_mode().
Referenced by main().
help()
int help (void)
Выводит информацию о каждом допустимом аргументе командной строки
Returns
Возвращает 0 - успешное завершение программы
Definition at line 47 of file command_line_unit.cpp.
               {
    for (size_t iter = 0; iter < sizeof(arg_array)/sizeof(arg_array[0]); iter++) {
        printf("%s\n", arg_array[iter].discription);
    }
    return 0;
}
References arg_array.
Referenced by start_program().