src/command_line_unit.cpp File Reference
Обеспечивает работу ввода аргументов командной строки
#include <string.h>
#include <stdio.h>
#include <assert.h>
#include `command_line_unit.h`
Functions
void check_args (int argc_cp, char **argv_cp, MODES *mode)
Просматривает аргументы командной строки для дальнейшей работы с каждым из них
int help (void)
Выводит информацию о каждом допустимом аргументе командной строки
void change_mode (MODES *mode, MODES md)
Меняет режим работы программы
Variables
static Cmd_arg arg_array []
Detailed Description
Обеспечивает работу ввода аргументов командной строки
Function Documentation
change_mode()
void change_mode (MODES * mode, MODES md)
Меняет режим работы программы
Parameters
 in,out mode Режим работы программы, который будет изменен
 in cur_md Режим работы программы, который будет активирован
Definition at line 60 of file command_line_unit.cpp.
                                        {
    switch (md) {
        case SOLVE:
            *mode = SOLVE;
            break;
        case TEST:
            *mode = TEST;
            break;
        case HELP:
            *mode = HELP;
            break;
        default:
            printf("Ошибка: неопознанный режим работы");
            break;
    }
}
References HELP, SOLVE, and TEST.
Referenced by check_args().
check_args()
void check_args (int argc_cp, char ** argv_cp, MODES * mode)
Просматривает аргументы командной строки для дальнейшей работы с каждым из них
Parameters
 in argc_cp Копия количества аргументов командной строки
 in argv_cp Копия аргументов командной строки
 in,out mode Режим работы, который может быть изменен благодаря аргументам командной строки
Definition at line 27 of file command_line_unit.cpp.
                                                          {
    for (int iter = 0; iter < argc_cp; iter++) {
        for (size_t arg_num = 0; arg_num < sizeof(arg_array)/sizeof(arg_array[0]); arg_num++) {
            if (
                strcmp(arg_array[arg_num].short_name, argv_cp[iter]) == 0 ||
                strcmp(arg_array[arg_num].full_name, argv_cp[iter]) == 0) {
                    change_mode(mode, arg_array[arg_num].mode);
            }
        }
    }
}
References arg_array, and change_mode().
Referenced by main().
help()
int help (void)
Выводит информацию о каждом допустимом аргументе командной строки
Returns
Возвращает 0 - успешное завершение программы
Definition at line 47 of file command_line_unit.cpp.
               {
    for (size_t iter = 0; iter < sizeof(arg_array)/sizeof(arg_array[0]); iter++) {
        printf("%s\n", arg_array[iter].discription);
    }
    return 0;
}
References arg_array.
Referenced by start_program().
Variable Documentation
arg_array
Cmd_arg arg_array[] [static]
Initial value:
= {
    {SOLVE, "-s", "--solve_mode", "-s или --solve_mode - Решение квадратного уравнения\n"},
    {TEST, "-t", "--test_mode", "-t или --test_mode - Тестирование работы программы\n"},
    {HELP, "-h", "--help", "-h или --help - Вывести данные о принимаемых аргументах\n"}
}
Definition at line 13 of file command_line_unit.cpp.
Referenced by check_args(), and help().