src/input_output.cpp File Reference
Обеспечивает ввод и вывод программы
#include <stdio.h>
#include <assert.h>
#include <TXlib.h>
#include `input_output.h`
#include `square_equation_struct.h`
Functions
static void skip_char_line (void)
void data_input (sqr_eq *ptr_eq)
Функция, обрабатывающая входные данные для квадратного уравнения
int show_result (equation_type root_count, roots rts)
Выводит результат работы квадратного уравнения в поток вывода
Detailed Description
Обеспечивает ввод и вывод программы
Function Documentation
data_input()
void data_input (sqr_eq * ptr_eq)
Функция, обрабатывающая входные данные для квадратного уравнения
Parameters
 in,out ptr_eq Указатель на структуру квадратного уравнения
Принимает указатель на структуру квадратного уравнения и записывает в ее коэффициенты данные из потока ввода
Definition at line 29 of file input_output.cpp.
                                {
    assert(ptr_eq != NULL);
    const int correct_var_count = 3;
    int var_count = 0;
    while (var_count != correct_var_count) {
        var_count = scanf("%lf %lf %lf", &ptr_eq->cfs.first,
                                         &ptr_eq->cfs.second,
                                         &ptr_eq->cfs.third);
        }
        if (var_count != correct_var_count) {
            printf("Ошибка: неправильный ввод данных, повторите попытку:\n");
            skip_char_line();
        }
}
References sqr_eq::cfs, coeffs::first, coeffs::second, skip_char_line(), and coeffs::third.
Referenced by solve_mode_start().
show_result()
int show_result (equation_type root_count, roots rts)
Выводит результат работы квадратного уравнения в поток вывода
Parameters
 in root_count Количество корней квадратного уравнения, определяющее дальнейший вывод данных программы
 in rts Структура данных, содержащая корни решенного квадратного уравнения
Returns
0 - при правильном завершении работы программы, 1 - при ошибке
Definition at line 63 of file input_output.cpp.
                                                     {
    switch (root_count) {
        case zero_root_eq:
            printf("У данного уравнения нет решений\n");
            return 0;
        case infinity_root_eq:
            printf("У данного уравнения существует бесконечно много решений\n");
            return 0;
        case one_root_eq:
            printf("У данного уравнения существует один корень:\n\tx = %.3f\n", rts.x1);
            return 0;
        case two_root_eq:
            printf("У данного уравнения существует два корня:\n\tx1 = %.3f\n\tx2 = %.3f\n", rts.x1,
                                                                                          rts.x2);
            return 0;
        case error:
            return 1;
        default:
            printf("Ошибка: неопознанное значение количества корней\n");
            return 2;
    }
}
References error, infinity_root_eq, one_root_eq, two_root_eq, roots::x1, roots::x2, and zero_root_eq.
Referenced by solve_mode_start().
skip_char_line()
void skip_char_line (void) [static]
Убирает неверные данные из потока ввода, чистит карму, приносит удачу
Definition at line 95 of file input_output.cpp.
                         {
    while (getchar() != '\n');
}
Referenced by data_input().