headers/solver.h File Reference
Заголовочный файл для решения квадратного уравнения
#include `input_output.h`
#include `square_equation_struct.h`
Enumerations
enum cmp { less_than_zero = -1
, equal_zero
, more_than_zero
 }
Functions
equation_type square_solver (sqr_eq *ptr_eq)
Решение квадратного уравнения
cmp dbl_zero_cmp (double number)
Сравнение числа типа double с нулем
equation_type linear_eq_solver (sqr_eq *ptr_eq)
Частный случай для решения линейного уравнения
Detailed Description
Заголовочный файл для решения квадратного уравнения
Enumeration Type Documentation
cmp
enum cmp
Enumerator
less_than_zero Перечисление типов сравнения числа с нулем Меньше нуля
equal_zero Равно нулю
more_than_zero Больше нуля
Definition at line 12 of file solver.h.
         {
    less_than_zero = -1,
    equal_zero,
    more_than_zero
};
Function Documentation
dbl_zero_cmp()
cmp dbl_zero_cmp (double number)
Сравнение числа типа double с нулем
Definition at line 18 of file solver.cpp.
                            {
    const double accuracy = 1e-6;
    if (n1 > accuracy)
        return more_than_zero;
    else if (fabs(n1) < accuracy)
        return equal_zero;
    else
        return less_than_zero;
}
References equal_zero, less_than_zero, and more_than_zero.
Referenced by square_solver().
linear_eq_solver()
equation_type linear_eq_solver (sqr_eq * ptr_eq)
Частный случай для решения линейного уравнения
Definition at line 77 of file solver.cpp.
                                               {
    ptr_eq->rts.x1 = (-ptr_eq->cfs.third / ptr_eq->cfs.second);
    return one_root_eq;
}
References sqr_eq::cfs, one_root_eq, sqr_eq::rts, coeffs::second, coeffs::third, and roots::x1.
Referenced by square_solver().
square_solver()
equation_type square_solver (sqr_eq * ptr_eq)
Решение квадратного уравнения
Parameters
 in ptr_eq Указатель на структуру квадратного уравнения
Returns
Тип квадратного уравнения
Функция решает квадратное уравнение исходя из заданных в структуре коэффициентов: корни уравнения записываются в структуру, а на выход поступает тип квадратного уравнения, который впоследствии обрабатывается функцией вывода
Definition at line 42 of file solver.cpp.
                                            {
    assert(ptr_eq != NULL);
    if (dbl_zero_cmp(ptr_eq->cfs.first) == equal_zero) {
        if (dbl_zero_cmp(ptr_eq->cfs.second) == equal_zero) {
            return (dbl_zero_cmp(ptr_eq->cfs.third) == equal_zero) ? infinity_root_eq : zero_root_eq;
        }
        equation_type result = linear_eq_solver(ptr_eq);
        ptr_eq->rts.x2 = ptr_eq->rts.x1;
        return result;
    }
    double disc = ptr_eq->cfs.second * ptr_eq->cfs.second - 4 * ptr_eq->cfs.first * ptr_eq->cfs.third;
    switch (dbl_zero_cmp(disc)) {
        case more_than_zero: {
            double sqrt_disc = sqrt(disc);
            ptr_eq->rts.x1 = (-ptr_eq->cfs.second + sqrt_disc)/(2 * ptr_eq->cfs.first);
            ptr_eq->rts.x2 = (-ptr_eq->cfs.second - sqrt_disc)/(2 * ptr_eq->cfs.first);
            return two_root_eq;
        }
        case equal_zero:
            ptr_eq->rts.x1 = ptr_eq->rts.x2 = (-ptr_eq->cfs.second)/(2 * ptr_eq->cfs.first);
            return one_root_eq;
        case less_than_zero:
            return zero_root_eq;
        default:
            printf("Ошибка: неверное значение сравнения с нулем");
            return error;
    }
}
References sqr_eq::cfs, dbl_zero_cmp(), equal_zero, error, coeffs::first, infinity_root_eq, less_than_zero, linear_eq_solver(), more_than_zero, one_root_eq, sqr_eq::rts, coeffs::second, coeffs::third, two_root_eq, roots::x1, roots::x2, and zero_root_eq.
Referenced by solve_mode_start(), and test_iteration().