src/square_solver.cpp File Reference
Запускает ввод и вывод данных и решение квадратного уравнения
#include <TXLib.h>
#include <equation_type.h>
#include `input_output.h`
#include `solver.h`
#include `square_equation_struct.h`
#include `unit_test.h`
#include `square_solver.h`
Functions
int solve_mode_start ()
Обеспечивает работу ввода, вывода и решения квадратного уравнения
Detailed Description
Запускает ввод и вывод данных и решение квадратного уравнения
Function Documentation
solve_mode_start()
int solve_mode_start (void)
Обеспечивает работу ввода, вывода и решения квадратного уравнения
Returns
Возвращает 0, если программа выполняется без ошибок, иначе - число, отличное от нуля
Definition at line 20 of file square_solver.cpp.
                       {
    int output = 0;
    printf("# Программа решения квадратных уравнений\n"
           "# Введите через пробел коэффициенты квадратного уравнения:\n");
    sqr_eq eq = {};
    data_input(&eq);
    equation_type root_count = square_solver(&eq);
    output = show_result(root_count, eq.rts);
    return output;
}
References data_input(), sqr_eq::rts, show_result(), and square_solver().
Referenced by start_program().