src/square_solver_main_program.cpp File Reference
Обеспечивает работу всей программы
#include <stdio.h>
#include <stdlib.h>
#include <TXlib.h>
#include `unit_test.h`
#include `square_solver.h`
#include `command_line_unit.h`
Functions
int start_program (MODES md)
Запускает программу в выбранном режиме
int main (int argc, char *argv[])
Detailed Description
Обеспечивает работу всей программы
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 17 of file square_solver_main_program.cpp.
                                 {
    MODES main_mode = SOLVE;
    if (argc > 1) {
        check_args(argc, argv, &main_mode);
    }
    return start_program(main_mode);
}
References check_args(), SOLVE, and start_program().
start_program()
int start_program (MODES md)
Запускает программу в выбранном режиме
Parameters
 in md Тип запускаемого режима
Returns
Возвращает 0 при успешном завершении программы, иначе - ненулевое значение
Definition at line 33 of file square_solver_main_program.cpp.
                            {
    switch (md) {
        case SOLVE:
            return solve_mode_start();
        case TEST:
            unit_test_start();
            return 0;
        case HELP:
            return help();
        default:
            txSetConsoleAttr(2);
            printf("Ошибка: неизвестый режим работы программы\n");
            txSetConsoleAttr(15);
            return -1;
    }
}
References HELP, help(), SOLVE, solve_mode_start(), TEST, and unit_test_start().
Referenced by main().