headers/unit_test.h File Reference
Заголовочный файл для модуля тестирования
#include `square_equation_struct.h`
Functions
void unit_test_start ()
Запускает модуль тестирования
Detailed Description
Заголовочный файл для модуля тестирования
Function Documentation
unit_test_start()
void unit_test_start ()
Запускает модуль тестирования
Definition at line 31 of file unit_test.cpp.
                           {
    FILE* ptr_to_file = fopen("data/answers.txt", "r");
    if (ptr_to_file == NULL) {
            perror ("Cannot open answers.txt");
            return;
    }
    int line_count = 0, test_num = 0;
    expected_eq ex_eq = {};
    fscanf(ptr_to_file, "%i", &line_count);
    for (; line_count > 0; line_count--) {
        fscanf(ptr_to_file, "%lf %lf %lf %lf %lf %i\n", &ex_eq.test_eq.cfs.first,
                                                        &ex_eq.test_eq.cfs.second,
                                                        &ex_eq.test_eq.cfs.third,
                                                        &ex_eq.correct_roots.x1,
                                                        &ex_eq.correct_roots.x2,
                                                        &ex_eq.correct_root_count);
        change_root_to_zero(&ex_eq);
        test_iteration(test_num, &ex_eq);
        test_num++;
    }
    fclose (ptr_to_file);
}
References sqr_eq::cfs, change_root_to_zero(), expected_eq::correct_root_count, expected_eq::correct_roots, coeffs::first, coeffs::second, expected_eq::test_eq, test_iteration(), coeffs::third, roots::x1, and roots::x2.
Referenced by start_program().