src/unit_test.cpp File Reference
Обеспечивает тестирование программы для проверки корректности работы
#include <stdlib.h>
#include <assert.h>
#include <TXLib.h>
#include `square_equation_struct.h`
#include `solver.h`
#include `unit_test.h`
Classes
struct expected_eq
Объявление структры для проверки работы основной программы
Functions
static int is_double_num_equal (double num1, double num2)
Вспомогательная функция для сравнивания чисел типа double.
static void test_iteration (int test_num, expected_eq *ptr_ex_eq)
Сравнивает результат работы программы с ожидаемым результом и при несоответствии выводит ошибку
static void change_root_to_zero (expected_eq *ptr_ex_eq)
Сбрасывает значения корней на стандартные для корректной работы программы
static int compare_correct_and_test_roots (expected_eq *peq)
Сравнивание чисел типа double.
void unit_test_start (void)
Запускает модуль тестирования
Detailed Description
Обеспечивает тестирование программы для проверки корректности работы
Function Documentation
change_root_to_zero()
static void change_root_to_zero (expected_eq * ptr_ex_eq) [static]
Сбрасывает значения корней на стандартные для корректной работы программы
Definition at line 98 of file unit_test.cpp.
                                                        {
    assert(ptr_ex_eq != NULL);
    ptr_ex_eq->test_eq.rts.x1 = 0;
    ptr_ex_eq->test_eq.rts.x2 = 0;
}
References expected_eq::test_eq.
Referenced by unit_test_start().
compare_correct_and_test_roots()
static int compare_correct_and_test_roots (expected_eq * peq) [static]
Сравнивание чисел типа double.
Definition at line 108 of file unit_test.cpp.
                                                             {
    return (is_double_num_equal(peq->test_eq.rts.x1, peq->correct_roots.x1) &&
            is_double_num_equal(peq->test_eq.rts.x2, peq->correct_roots.x2));
}
References expected_eq::correct_roots, is_double_num_equal(), and expected_eq::test_eq.
Referenced by test_iteration().
is_double_num_equal()
static int is_double_num_equal (double num1, double num2) [static]
Вспомогательная функция для сравнивания чисел типа double.
Definition at line 114 of file unit_test.cpp.
                                                        {
    const double accuracy = 0.01;
    return (fabs(num1 - num2) < accuracy);
}
Referenced by compare_correct_and_test_roots().
test_iteration()
static void test_iteration (int test_num, expected_eq * ptr_ex_eq) [static]
Сравнивает результат работы программы с ожидаемым результом и при несоответствии выводит ошибку
Parameters
 in test_num Номер теста для удобства отслеживания места ошибки
 in,out ptr_ex_eq Указатель на структуру для проверки работы основной программы
Definition at line 69 of file unit_test.cpp.
                                                                {
    int root_count = square_solver(&ptr_ex_eq->test_eq);
    if (root_count != ptr_ex_eq->correct_root_count || !compare_correct_and_test_roots(ptr_ex_eq)) {
        txSetConsoleAttr(4);
        printf("Ошибка в тесте №%d\n"
               "Итоговые значения: root_count = %d, x1 = %lg, x2 = %lg\n"
               "Ожидаемые значения: root_count = %d, x1 = %lg, x2 = %lg\n"
               "\n",
                test_num+1,
                root_count,
                ptr_ex_eq->test_eq.rts.x1,
                ptr_ex_eq->test_eq.rts.x2,
                ptr_ex_eq->correct_root_count,
                ptr_ex_eq->correct_roots.x1,
                ptr_ex_eq->correct_roots.x2);
        txSetConsoleAttr(15);
    }
    else {
        txSetConsoleAttr(2);
        printf("Тест №%d пройден успешно\n", test_num+1);
        txSetConsoleAttr(15);
    }
}
References compare_correct_and_test_roots(), expected_eq::correct_root_count, expected_eq::correct_roots, square_solver(), and expected_eq::test_eq.
Referenced by unit_test_start().
unit_test_start()
void unit_test_start (void)
Запускает модуль тестирования
Definition at line 31 of file unit_test.cpp.
                           {
    FILE* ptr_to_file = fopen("data/answers.txt", "r");
    if (ptr_to_file == NULL) {
            perror ("Cannot open answers.txt");
            return;
    }
    int line_count = 0, test_num = 0;
    expected_eq ex_eq = {};
    fscanf(ptr_to_file, "%i", &line_count);
    for (; line_count > 0; line_count--) {
        fscanf(ptr_to_file, "%lf %lf %lf %lf %lf %i\n", &ex_eq.test_eq.cfs.first,
                                                        &ex_eq.test_eq.cfs.second,
                                                        &ex_eq.test_eq.cfs.third,
                                                        &ex_eq.correct_roots.x1,
                                                        &ex_eq.correct_roots.x2,
                                                        &ex_eq.correct_root_count);
        change_root_to_zero(&ex_eq);
        test_iteration(test_num, &ex_eq);
        test_num++;
    }
    fclose (ptr_to_file);
}
References change_root_to_zero(), expected_eq::correct_root_count, expected_eq::correct_roots, expected_eq::test_eq, and test_iteration().
Referenced by main().